version: "3.3"
services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
#    user: '1000'
#    command: ['tail', '-f', '/dev/null']
#    command: ['composer', 'install']

