services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
    command: ['composer', 'install']
    # for manual debug
    #command: ['tail', '-f', '/dev/null']

